# Generated by Django 4.0.5 on 2022-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('anios', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
