# Generated by Django 4.0.5 on 2022-07-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/images/rescatados'),
        ),
    ]
